### ISSUE TITLE
Doesn't work!

### ISSUE THREAD

**Issue by LIttleAncientForestKami** [afornalik/magic-number#1]
Session log
```
[tammo@lafk-T470 src]$ java afornalik.Main                                                                                                                                                                [INSERT]
java.io.FileNotFoundException: /home/tammo/tmp/magic-number/src\samples\task1.pdf (Nie ma takiego pliku ani katalogu)
	at java.base/java.io.FileInputStream.open0(Native Method)
	at java.base/java.io.FileInputStream.open(FileInputStream.java:219)
	at java.base/java.io.FileInputStream.<init>(FileInputStream.java:157)
	at afornalik.service.FileService.returnFirstByteFromFile(FileService.java:19)
	at afornalik.Main.main(Main.java:29)
 Extension not supported 
```

**Comment by afornalik** [comment]
I just created small fix to issue, but You need to specify file to be checked.
